const data=[
{
    name: 'Chicken Broiler (Skin off)',
    description: 'The best chickens are sourced from our partnered farms and processed in our processing unit under expert supervision before the final product is delivered at your doorsteps. The live weight of the chicken is approximately 1.5kgs. After processing and removing the skin, feathers and other waste the meat weight remains at 1kg +- 50gms. ',
    features: [
        'Healthy chicken from certified farms',
        'Best quality chickens are processed and delivered at your doorsteps',
        'Ready to cook',
    ],
    price: 500,
    unit: 'Pcs',
    category: 'chicken',
    code: 'LF01001',
    images: [],
},
{
    name: 'Sonali Chicekn',
    description: 'Sonali chicken contains less fat percentage than broiler chicken and is perfect for traditional recipes. The chicken is processed in our processing unit under expert supervision and 100% hygienic guidelines are maintained. There are 2 weight variants available for Sonali chicken at LiveFresh.',
    specs: [
        { title: 'Liveweight', value: '1 Kg' },
        { title: 'Meatweight', value: '550 Gram' },
        { title: 'Liveweight', value: '600 Gram' },
        { title: 'Meatweight', value: '300 Gram' },
    ],
    features: [
        'Perfect lean protein diet',
        'Contains minerals and vitamins',
        'Can be served grilled or cooked traditionally',
        'Home delivered after quality checked by expert',
        'Ready to cook',
    ],
    price: 500,
    unit: 'Pcs',
    category: 'chicken',
    code: 'LF01002',
    images: [],
  
},
{
    name: 'Chicken Broiler (Skin on)',
    description: 'The best chickens are sourced from our partnered farms and processed in our processing unit under expert supervision before the final product is delivered at your doorsteps. The live weight of the chicken is approximately 1.5kgs. After processing and removing the feathers and other waste the meat weight remains at 1kg +- 50gms.',
    features: [
        'Healthy chicken from certified farms',
        'Best quality chickens are processed and delivered at your doorsteps',
        'Ready to cook',
    ],
    price: 500,
    unit: 'Pcs',
    category: 'chicken',
    code: 'LF01003',
    images: [],
},
{
    name: 'Chicken Breast (Boneless)',
    description: 'A 100gm of chicken breast contains approximately 31gms of protein and 3.5gms of fat. The chicken breast is one of the meatier parts of the chicken. The skin and bone is removed carefully to provide a succulent breast piece.',
    features: [
        'Perfect lean protein diet',
        'Contains minerals and vitamins',
        'Can be served grilled or cooked traditionally',
        'Home delivered after quality checked by expert',
        'Ready to cook',
    ],
    price: 500,
    unit: 'Pcs',
    category: 'sides',
    code: 'LF02001',
    images: [],
},
{
    name: 'Chicken Drumstick',
    description: 'Tender and flavorful drumsticks which are freshly processed and delivered. The drumsticks are of similar sizes each.',
    features: [
        'Available in 500grams and 1kg packages',
        'Freshly delivered at your doorsteps',
        'Ready to cook',
    ],
    price: 500,
    unit: 'Pcs',
    category: 'sides',
    code: 'LF02002',
    images: [],
},
{
    name: 'Chicken thigh (Bone in)',
    description: 'The chicken thighs are freshly cut and processed in our processing unit by experts. These portions are tender and juicy with a silken texture. This portion is perfect for making Garlic Chicken, Chicken Biryani, Tandoori Chicken, Pepper Chicken etc.',
    features: [
        'Freshly delivered at your doorsteps',
        'Ready to cook',
    ],
    price: 500,
    unit: 'Pcs',
    category: 'sides',
    code: 'LF02003',
    images: [],
},
{
    name: 'Chicken thigh (Bone less)',
    description: 'The chicken thighs are freshly cut and processed in our processing unit by experts. These portions are tender and juicy with a silken texture. The best part is you do not have to deal with the bones as it is removed during our processing.',
    features: [
        'Freshly delivered at your doorsteps',
        'Ready to cook',
    ],
    price: 500,
    unit: 'Pcs',
    category: 'sides',
    code: 'LF02004',
    images: [],
},
{
    name: 'Chicken Wings',
    description: 'Fresh wings are directly cut from the chicken and washed properly before delivering it to your hands.',
    features: [
        'Freshly delivered at your doorsteps',
        'Ready to cook',
    ],
    price: 500,
    unit: 'Pcs',
    category: 'sides',
    code: 'LF02005',
    images: [],
},
{
    name: 'Breast Fillet',
    description: '',
    features: [
        'Freshly delivered at your doorsteps',
        'Ready to cook',
    ],
    price: 500,
    unit: 'Pcs',
    category: 'sides',
    code: 'LF02006',
    images: [],
},
{
    name: 'Chicken Full Leg',
    description: '',
    features: [
        'Freshly delivered at your doorsteps',
        'Ready to cook',
    ],
    price: 500,
    unit: 'Pcs',
    category: 'sides',
    code: 'LF02007',
    images: [],
},
{
    name: 'Chicken Full Leg (Skin Off)',
    description: '',
    features: [
        'Freshly delivered at your doorsteps',
        'Ready to cook',
    ],
    price: 500,
    unit: 'Pcs',
    category: 'sides',
    code: 'LF02008',
    images: [],
},
{
    name: 'Chicken Offal',
    description: '',
    features: [
        'Freshly delivered at your doorsteps',
        'Ready to cook',
    ],
    price: 500,
    unit: 'Pcs',
    category: 'sides',
    code: 'LF02009',
    images: [],
},
{
    name: 'Beef (Bone less)',
    description: 'Only the most healthy and well grown beef is chosen and processed to provide you with succulent and tender beef pieces. The bones are removed and the pieces are cut to make the product ready to cook. The whole process is done under expert supervision and in a 100% hygienic environment.',
    features: [
        'Get what you ordered',
        'Properly washed and ready to cook',
    ],
    price: 500,
    unit: 'Pcs',
    category: 'beef',
    code: 'LF03001',
    images: [],
},
{
    name: 'Beef Bone-in',
    description: '',
    features: [
        'Get what you ordered',
        'Properly washed and ready to cook',
    ],
    price: 500,
    unit: 'Pcs',
    category: 'beef',
    code: 'LF03002',
    images: [],
},
{
    name: 'Beef Liver',
    description: '',
    features: [
        'Get what you ordered',
        'Properly washed and ready to cook',
    ],
    price: 500,
    unit: 'Pcs',
    category: 'beef',
    code: 'LF03003',
    images: [],
},
{
    name: 'Beef Paya',
    description: '',
    features: [
        'Get what you ordered',
        'Properly washed and ready to cook',
    ],
    price: 500,
    unit: 'Pcs',
    category: 'beef',
    code: 'LF03004',
    images: [],
},
]
